Foodsquare/urls.py
from django.contrib import admin
from django.urls import path, include

# if settings.DEBUG:
#     import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	# path(r'browse/', include('browse.urls'),name='browse'),
	path(r'', include('browse.urls'), name='home'),
	path(r'accounts/', include('accounts.urls'), name="accounts"),
	path(r'customer/', include('customer.urls'), name="customer"),
	path(r'manager/', include('manager.urls'), name="manager"),
	path('admin/', admin.site.urls),
	path(r'accounts/', include('allauth.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

browse/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from browse import views

app_name = 'browse'

urlpatterns = [
	path('', views.Index.as_view(), name='home'),
	path('browse/', views.OrderView.as_view(), name='package-list'),
	path('offer/', views.OfferView, name='offer-list'),
	path('about/', views.aboutSection),
	path('contact/', views.contactSection),
	path('branch_pkg_availability/', views.branch_pkg_availability),
	path('browse/filter/', views.FilteredProducts, name='rating_filter'),

	path('browse/restaurants/', views.RestaurantList.as_view(), name='restaurants'),
	path('browse/branches/', views.RestaurantList.as_view(), name='branches'),

	# path('menuEntryForRestaurant/', views.RestaurantMenuEntryList.as_view()),
	# path('branchListForRestaurant/', views.RestaurantBranchList.as_view())
	path('browse/raw/', views.viewRaw),

	path('browse/item/<int:id>/', views.PackageDetails.as_view(), name='package-details'),
	path('browse/item/<int:id>/submitReview/', views.submitReview),
	path('browse/item/<int:id>/submitRating/', views.submitPackageRating),
	path('browse/item/<int:id>/reactOn/', views.reactSubmit),

	path('browse/restaurants/<int:id>/', views.RestaurantDetails.as_view(), name='restaurant_detail'),

	path('browse/branches/<int:id>/', views.RestaurantBranchDetails.as_view(), name='Branch_detail'),
	path('browse/branches/<int:id>/submitRating/', views.submitBranchRating),
	path('browse/branches/<int:id>/submitReview/', views.submitReview),
	path('browse/branches/<int:id>/reactOn/', views.reactSubmit),

	path('order/checkout/', views.CheckoutView.as_view(), name='checkout'),
	path('order/checkout/bkashPayment', views.bkashPayment, name='bkashPayment'),

]

urlpatterns = format_suffix_patterns(urlpatterns)

customer/urls.py
from django.urls import path

from . import views

app_name = 'customer'
urlpatterns = [
	path('editProfile/', views.EditProfileView.as_view()),
	path('myOrders/', views.myOrdersList.as_view(), name='homepage'),
	path('submitDeliveryRating/', views.submitDeliveryRating),
	path('get_notifications/', views.get_notifications),
	path('read_notifications/', views.read_notifcations),

]

customer/models.py
from django.db import models


class Notification(models.Model):
	"""Notifications for any system user"""
	message = models.CharField(verbose_name="Message", max_length=250, blank=False, null=False)
	time = models.DateTimeField(verbose_name="Notification Push Time", auto_now_add=True)
	read = models.BooleanField(verbose_name="Notification has been read", default=False)
	read_time = models.DateTimeField(verbose_name="Notification read time", auto_now_add=False, null=True)

	user = models.ForeignKey('accounts.User', on_delete=models.CASCADE, related_name="notification_target_user")

	def mark_as_read(self):
		from datetime import datetime
		self.read = True
		self.read_time = datetime.now()
		self.save()

	@staticmethod
	def send_notification(user, text):
		notification = Notification(user=user, message=text)
		notification.save()

	@staticmethod
	def get_unread_notifications(user):
		return Notification.objects.filter(user=user, read=False).order_by('-time')

	@staticmethod
	def get_all_notifications(user, time=None):
		""" Get all notifications arrived after provided time at descending order """
		return Notification.objects.filter(user=user, time__gt=time).order_by('-time')

customer/views.py
from allauth.socialaccount.models import SocialAccount
from django.http import HttpResponse
from django.http import JsonResponse
# Create your views here.
from django.shortcuts import render
from django.urls import reverse
from django.views.generic import TemplateView, ListView

from accounts.forms import UserForm, ProfileForm
from accounts.models import User, Order
from accounts.utils import pretty_request


class EditProfileView(TemplateView):
	template_name = 'customer/EditProfile.html'

	def get(self, request, *args, **kwargs):

		return super(self.__class__, self).get(request, *args, **kwargs)

	def get_context_data(self, *args, **kwargs):
		context = super(EditProfileView, self).get_context_data(**kwargs)
		print(pretty_request(self.request))
		try:
			obj = dict()
			context['userprofile'] = User.objects.get(id=self.request.user.id).userprofile
			context['socialacnt'] = False

		except Exception as e:
			obj = dict()
			obj = SocialAccount.objects.get(user_id=self.request.user.id).extra_data
			context['socialacnt'] = True
			try:  # for facebook
				obj['avatar'] = obj['picture']
				del obj['picture']
			except Exception as e1:
				pass
			context['userprofile'] = obj
			print(context)
		return context

	def post(self, request, *args, **kwargs):
		print(request)
		oldUser = User.objects.get(id=request.user.id)
		user_form = UserForm(request.POST, oldUser)
		profile = oldUser.userprofile
		profile.user = oldUser
		profile_form = ProfileForm(request.POST or None, request.FILES or None, instance=profile)
		print(profile_form)
		if profile_form.is_valid():
			profile_form.save()
			print('Registering : ' + str(request.user))
			return render(request, 'accounts/message_page.html',
						  {'header': "Signed Up!", 'details': '',
						   'redirect': reverse('customer:homepage')})

		else:
			return render(request, 'accounts/message_page.html',
						  {'header': "Error!", 'details': 'Try Again',
						   'redirect': reverse('customer:homepage')})
		pass


class myOrdersList(ListView):
	template_name = 'customer/trackOrder.html'
	context_object_name = 'Orders'

	def get_queryset(self):
		return Order.objects.filter(user=self.request.user)


def get_notifications(request):
	from customer.utils_db import get_unread_notifications
	unreads = get_unread_notifications(request.user)
	if unreads is not None:
		notifications = [notf.message for notf in unreads]
	else:
		notifications = []
	return JsonResponse({'notifications': notifications})


def read_notifcations(request):
	from datetime import datetime
	from customer.utils_db import read_all_notifications
	read_all_notifications(request.user, datetime.now())
	return JsonResponse({'Success': True})


def submitDeliveryRating(request):
	order_id = request.POST.get('order-id')
	rating = request.POST.get('rating')
	print(order_id)
	print(rating)
	from browse.utils_db import post_delivery_rating
	return JsonResponse({'success': post_delivery_rating(order_id, rating)})

customer/templates/customer/EditProfile.html
{% extends 'customer/base.html' %}

{% block header %}
    <title>{{ request.user.username | capfirst }} | Profile | FoodSquare </title>
{% endblock %}


{% block body-content %}
    <div class="page-inner">
        {% if request.user.is_suspended %}
            <h1 style="color: red">&nbsp;&nbsp;&nbsp;Your account has been suspended.</h1>
            <h1 style="color: red">&nbsp;&nbsp;&nbsp;Contact us at <a
                    href="mailto:{{ request.user.get_suspend_contact_email }}">{{ request.user.get_suspend_contact_email }}</a>
            </h1>
        {% endif %}
        <div id="main-wrapper">
            <div class="container">
                <h1>Edit Profile</h1>
                <hr>
                <div class="row">
                    <!-- left column -->
                    <form method="post" enctype="multipart/form-data" class="form-horizontal" role="form">
                        {% csrf_token %}
                        <div class="col-md-3">
                            <div class="text-center">

                                {% if not socialacnt %}
                                    <img id="current_image" src={{ userprofile.avatar.url }} class="avatar"
                                         style="width: 100%;height: 100%" alt="avatar">
                                {% else %}
                                    <img id="current_image" src="{{ userprofile.avatar }}" class="avatar"
                                         style="width: 100%;height: 100%" alt="avatar">
                                {% endif %}
                                <br>
                                <br>
                                <h5>Upload a different photo...</h5>

                                <input type="file" name="image" id="selected_image" class="form-control"
                                       onchange="updateImg()">
                                <script>
                                    function updateImg() {
                                        var fReader = new FileReader();
                                        fReader.readAsDataURL(document.getElementById("selected_image").files[0]);
                                        fReader.onloadend = function (event) {
                                            document.getElementById("current_image").src = event.target.result;
                                        }
                                    }
                                </script>
                            </div>
                        </div>

                        <!-- edit form column -->
                        <div class="col-md-9 personal-info">
                            {#                            <div class="alert alert-info alert-dismissable">#}
                            {#                                <a class="panel-close close" data-dismiss="alert">×</a>#}
                            {#                                <i class="fa fa-coffee"></i>#}
                            {#                                This is an <strong>.alert</strong>. Use this to show important messages to the user.#}
                            {#                            </div>#}
                            <h3>Personal info</h3>


                            <div class="form-group">
                                <label class="col-lg-3 control-label">First name:</label>
                                <div class="col-lg-8">
                                    <input class="form-control" type="text" name="first_name"
                                           value={{ userprofile.first_name }}>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-3 control-label">Last Name:</label>
                                <div class="col-lg-8">
                                    <input class="form-control" type="text" name="last_name"
                                           value={{ userprofile.last_name }}>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-3 control-label">Address:</label>
                                <div class="col-lg-8">
                                    <input class="form-control" type="text" name="address"
                                           value={{ userprofile.address }}>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-lg-3 control-label">Email:</label>
                                <div class="col-lg-8">
                                    <input class="form-control" type="text" name="email" value={{ request.user.email }}>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-3 control-label">Username:</label>
                                <div class="col-md-8">
                                    <input class="form-control" type="text" value={{ request.user.username }}
                                            name="username">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">Password:</label>
                                <div class="col-md-8">
                                    <input class="form-control" type="password" value="11111122333" name="password">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">Confirm password:</label>
                                <div class="col-md-8">
                                    <input class="form-control" type="password" value="11111122333" name="re_pass">
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label"></label>
                                <div class="col-md-8">
                                    <input type="submit" class="btn btn-primary" value="Save Changes">
                                    <span></span>
                                    <input type="reset" class="btn btn-default" value="Cancel">
                                </div>
                            </div>
                    </form>
                </div>
            </div>
        </div>
        <hr>

    </div>
{% endblock %}

customer/templates/customer/notifications.html
{#<a href="#" class="dropdown-toggle waves-effect waves-button waves-classic" id="noti_bell"#}
{#   data-toggle="dropdown"><i class="fa fa-bell"></i><span#}
{#        class="badge badge-success pull-right">{{ cnt }}</span></a>#}

{#<li>#}
{#                                    <p class="drop-title">You have 3 pending tasks !</p>#}
{#                                </li>#}
<script>
    {#        {% if cnt == "0" %}#}
    {#        document.getElementById('noti-count').textContent={{ cnt }};#}
    {#        {% endif %}#}
</script>
<li class="dropdown-menu-list slimscroll tasks">
    <ul class="list-unstyled">
        {% for ntfs in notifications %}

            <li>
                <a href="#">
                    <div class="task-icon badge badge-success"><i class="icon-user"></i>
                    </div>
                    <span class="badge badge-roundless badge-default pull-right">1min
                                                        ago</span>
                    <p class="task-details">{{ ntfs.message }}</p>

                </a>
            </li>
        {% endfor %}
    </ul>
</li>
{#                                <li class="drop-all"><a href="#" class="text-center">All Tasks</a></li>#}
{#<script>#}
{#    $(document).ready(function(){#}
{#        $('#noti_bell').click(function(){#}
{#            $.ajax({#}
{#                type: "GET",#}
{#                url: "/customer/read_notifications/",#}
{#                data: {#}
{##}
{#                },#}
{#                success: function(data)#}
{#                {#}
{#                    $('#notifications').html(data);#}
{#                }#}
{#            });#}
{#        });#}
{#    });#}
{#</script>#}
{#<script>#}
{#    function read_nofications() {#}
{#        #}
{#    }#}
{#</script>#}

customer/templates/customer/rate_submit.html
<style>
    .star-cb-group {
        /* remove inline-block whitespace */
        font-size: 0;
        /* flip the order so we can use the + and ~ combinators */
        unicode-bidi: bidi-override;
        direction: rtl;
        /* the hidden clearer */
    }

    .star-cb-group * {
        font-size: 1rem;
    }

    .star-cb-group > input {
        display: none;
    }

    .star-cb-group > input + label {
        /* only enough room for the star */
        display: inline-block;
        overflow: hidden;
        text-indent: 9999px;
        width: 1em;
        white-space: nowrap;
        cursor: pointer;
    }

    .star-cb-group > input + label:before {
        display: inline-block;
        text-indent: -9999px;
        content: '\2606';
        color: #888;
    }

    .star-cb-group > input:checked ~ label:before, .star-cb-group > input + label:hover ~ label:before, .star-cb-group > input + label:hover:before {
        content: '\2605';
        color: #e52;
        text-shadow: 0 0 1px #333;
    }

    .star-cb-group > .star-cb-clear + label {
        text-indent: -9999px;
        width: 0.5em;
        margin-left: -0.5em;
    }

    .star-cb-group > .star-cb-clear + label:before {
        width: 0.5em;
    }

    .star-cb-group:hover > input + label:before {
        content: '\2606';
        color: #888;
        text-shadow: none;
    }

    .star-cb-group:hover > input + label:hover ~ label:before, .star-cb-group:hover > input + label:hover:before {
        content: '\2605';
        color: #e52;
        text-shadow: 0 0 1px #333;
    }

    :root {
        font-size: 2em;
        font-family: Helvetica, arial, sans-serif;
    }

    body {
        background: #333;
        color: #888;
    }

    fieldset {
        border: 0;
        background: #222;
        width: 5em;
        border-radius: 1px;
        padding: 1em 1.5em 0.9em;
        margin: 1em auto;
    }

    #log {
        margin: 1em auto;
        width: 5em;
        text-align: center;
        background: transparent;
    }

    h1 {
        text-align: center;
    }

</style>
<input type="hidden" id="order_id">
<span class="star-cb-group">

</span>

customer/templates/customer/trackOrder.html
{% extends 'customer/base.html' %}

{% block header %}
    <title>{{ request.user.username | capfirst }} | Orders | FoodSquare </title>
{% endblock %}

{% block slidebar %}
    <li><a href="/homepage/" class="waves-effect waves-button"><span
            class="menu-icon glyphicon glyphicon-home"></span>
        <p>Orders</p>
    </a></li>
{% endblock %}

{% block body-content %}
    <div class="page-inner">
        {% load static %}
        <div class="col-lg-12 col-md-12">
            <div class="panel panel-white">
                <div class="panel-heading">
                    <h4 class="panel-title">Order List</h4>
                </div>

                <div class="panel-body">
                    <div class="table-responsive project-stats">
                        <table class="table">
                            <thead>
                            <tr>
                                <th>Order Id</th>
                                <th>Restaurant</th>

                                <th>Time</th>
                                <th>Order Status</th>
                                <th>Payment Type</th>
                                <th>Ref. No(if applicable)</th>
                                <th>Payment status</th>
                                <th>Pay Now</th>
                                <th>You've been rated</th>

                                <th>You rated</th>
                            </tr>
                            </thead>
                            <tbody>
                            {% for order in Orders %}
                                <tr>
                                    <td>{{ order.id }}</td>
                                    <td>{{ order.branch.branch_name }}</td>
                                    <td>{{ order.time }} </td>
                                    <td>
                                        {% if order.order_status == "PENDING" %}
                                            <span class="label label-danger">Pending for confirmation</span>
                                        {% elif order.order_status == "PROCESSING" %}
                                            <span class="label label-info">Pending for Delivery</span>
                                        {% elif order.order_status == "DELIVERING" %}
                                            <span class="label label-info">Delivery on the way</span>
                                        {% elif order.order_status == "DELIVERED" %}
                                            <span class="label label-success">Delivered</span>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if order.payment.payment_type == "C" %}
                                            Cash
                                        {% elif order.payment.payment_type == "O" %}
                                            Online
                                        {% endif %}
                                    </td>

                                    <td> {{ order.payment.bkash_ref }}</td>
                                    <td>
                                        {% if order.order_status == "DELIVERED" %}
                                            <span class="label label-danger">Cleared</span>
                                        {% elif order.payment.payment_status == "P" %}
                                            <span class="label label-danger">Paid</span>
                                        {% elif order.payment.payment_status == "D" %}
                                            <span class="label label-info">Due</span>

                                        {% endif %}
                                    </td>
                                    <td>
                                        {% if order.payment.payment_type == "O" and order.payment.payment_status == "D" %}
                                            <form action="{% url 'browse:bkashPayment' %}" method="GET">
                                                <button type="submit">Pay Now</button>
                                                <input type="hidden" name="ref-no" value="{{ order.payment.bkash_ref }}">
                                            </form>
                                        {% endif %}
                                    </td>
                                    <td>
                                        {{ order.delivery.rating_user }}
                                    </td>
                                    <td>
                                        {% if order.delivery.rating_deliveryman == None %}
                                            <a href="{{ order.id }}" class="order_rate"> Rate Now</a>

                                        {% else %}
                                            {{ order.delivery.rating_deliveryman }}
                                        {% endif %}
                                    </td>

                                    <td>
                                        {#                                        {% if order.delivery and d %}#}
                                    </td>

                                </tr>
                            {% endfor %}

                            </tbody>
                        </table>
                    </div>
                </div>
            </div>
        </div>

    </div>
    {#    {% include 'customer/rate_submit.html' %}#}

    <!-- Modal -->
    <div class="modal fade" id="delivery_modal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel"
         aria-hidden="true">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Rate Delivery </h5>

                </div>
                <div class="modal-body">
                    {% include 'customer/rate_submit.html' %}
                </div>
                <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
    <script src="{% static 'customer/js/ajax_upload.js' %}"></script>
    <script>
        $(document).ready(function () {

            $(".order_rate").click(function (event) {
                event.preventDefault();
                document.getElementsByClassName('star-cb-group')[0].innerHTML = "<input type=\"radio\" id=\"rating-5\" name=\"rating\" value=\"5\" /><label for=\"rating-5\">5</label>\n" +
                    "      <input type=\"radio\" id=\"rating-4\" name=\"rating\" value=\"4\" checked=\"checked\" /><label for=\"rating-4\">4</label>\n" +
                    "      <input type=\"radio\" id=\"rating-3\" name=\"rating\" value=\"3\" /><label for=\"rating-3\">3</label>\n" +
                    "      <input type=\"radio\" id=\"rating-2\" name=\"rating\" value=\"2\" /><label for=\"rating-2\">2</label>\n" +
                    "      <input type=\"radio\" id=\"rating-1\" name=\"rating\" value=\"1\" /><label for=\"rating-1\">1</label>\n" +
                    "      <input type=\"radio\" id=\"rating-0\" name=\"rating\" value=\"0\" class=\"star-cb-clear\" /><label for=\"rating-0\">0</label>";
                $('#order_id').val($(this).attr('href'));
                $("#delivery_modal").modal();
            });

        });

        $(document).on('change', '.star-cb-group input', function () {

            var rate_val = $("input[type='radio'][name='rating']:checked").val();
            var csrftoken = getCookie('csrftoken');
            {#alert(rate_val);#}
            $("#star3").prop("checked", true);

            $.ajax({
                type: "POST",
                headers: {
                    "X-CSRFToken": csrftoken
                },
                url: '/customer/submitDeliveryRating/',
                data: {
                    'order-id': $('#order_id').val(),
                    'rating': rate_val
                },
                dataType: 'json',
                success: function (data) {
location.reload();
                }
            });

        });
    </script>

{% endblock %}