Foodsquare/urls.py
from django.contrib import admin
from django.urls import path, include

# if settings.DEBUG:
#     import debug_toolbar
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
	# path(r'browse/', include('browse.urls'),name='browse'),
	path(r'', include('browse.urls'), name='home'),
	path(r'accounts/', include('accounts.urls'), name="accounts"),
	path(r'customer/', include('customer.urls'), name="customer"),
	path(r'manager/', include('manager.urls'), name="manager"),
	path('admin/', admin.site.urls),
	path(r'accounts/', include('allauth.urls')),
]

if settings.DEBUG:
	urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path, include

from accounts import views

app_name = 'accounts'

urlpatterns = [
	path('login/', views.LoginView.as_view(), name='login'),

	path('manager_login/', views.ManagerLoginView.as_view(), name='manger_login'),
	path('delivery_login/', views.DeliveryLoginView.as_view(), name='delivery_login'),
	path('manager_register/', views.ManagerRegisterView.as_view(), name='manager_register'),
	path('delivery_register/', views.DeliveryRegister.as_view(), name='delivery_register'),
	path('branch_register/', views.BranchRegisterView.as_view(), name='branch_register'),

	path('admin_login/', views.AdminLoginView.as_view(), name='admin_login'),

	path('register/', views.RegisterView.as_view(), name='register'),
	path(r'register/facebook-signUp/', include('allauth.urls'), name='facebook-signUp'),

	path('recovery/', views.recoveryRender, name='recovery'),

	path('logout/', views.LogoutView.as_view(), name='logout'),
	path('manager_logout/', views.ManagerLogoutView.as_view(), name='manager_logout'),
	path('delivery_logout/', views.ManagerLogoutView.as_view(), name='delivery_logout'),

	path('admin_logout/', views.ManagerLogoutView.as_view(), name='admin_logout'),

]

browse/urls.py
from django.urls import path
from rest_framework.urlpatterns import format_suffix_patterns

from browse import views

app_name = 'browse'

urlpatterns = [
	path('', views.Index.as_view(), name='home'),
	path('browse/', views.OrderView.as_view(), name='package-list'),
	path('offer/', views.OfferView, name='offer-list'),
	path('about/', views.aboutSection),
	path('contact/', views.contactSection),
	path('branch_pkg_availability/', views.branch_pkg_availability),
	path('browse/filter/', views.FilteredProducts, name='rating_filter'),

	path('browse/restaurants/', views.RestaurantList.as_view(), name='restaurants'),
	path('browse/branches/', views.RestaurantList.as_view(), name='branches'),

	# path('menuEntryForRestaurant/', views.RestaurantMenuEntryList.as_view()),
	# path('branchListForRestaurant/', views.RestaurantBranchList.as_view())
	path('browse/raw/', views.viewRaw),

	path('browse/item/<int:id>/', views.PackageDetails.as_view(), name='package-details'),
	path('browse/item/<int:id>/submitReview/', views.submitReview),
	path('browse/item/<int:id>/submitRating/', views.submitPackageRating),
	path('browse/item/<int:id>/reactOn/', views.reactSubmit),

	path('browse/restaurants/<int:id>/', views.RestaurantDetails.as_view(), name='restaurant_detail'),

	path('browse/branches/<int:id>/', views.RestaurantBranchDetails.as_view(), name='Branch_detail'),
	path('browse/branches/<int:id>/submitRating/', views.submitBranchRating),
	path('browse/branches/<int:id>/submitReview/', views.submitReview),
	path('browse/branches/<int:id>/reactOn/', views.reactSubmit),

	path('order/checkout/', views.CheckoutView.as_view(), name='checkout'),
	path('order/checkout/bkashPayment', views.bkashPayment, name='bkashPayment'),

]

urlpatterns = format_suffix_patterns(urlpatterns)

accounts/forms.py
from django import forms
from django.forms.models import ModelForm

from accounts.models import User
from .models import UserProfile, Restaurant, RestaurantBranch


class ProfileForm(ModelForm):
	class Meta:
		model = UserProfile
		fields = ('first_name', 'last_name', 'avatar', 'address')


class UserForm(ModelForm):
	password = forms.CharField(widget=forms.PasswordInput)

	class Meta:
		model = User
		fields = ('username', 'password', 'email')

	def save(self, commit=True):
		new_user = User.objects.create_user(username=self.cleaned_data['username'],
		                                    email=self.cleaned_data['email'],
		                                    password=self.cleaned_data['password'])
		try:
			new_user.first_name = self.cleaned_data['first_name']
			new_user.last_name = self.cleaned_data['last_name']
		except Exception:
			pass
		if commit:
			new_user.save()
		return new_user


class RestaurantForm(ModelForm):
	class Meta:
		model = Restaurant
		fields = ('restaurantImg',)


class RestaurantBranchForm(ModelForm):
	class Meta:
		model = RestaurantBranch
		fields = ('branch_name', 'branch_location', 'branch_location_details',)

	def save(self, commit=True):
		location = ''
		print('vai ksu hoy na')
		print(self.cleaned_data)
		print(self.cleaned_data['lat'])
		print(+ ',' + self.cleaned_data['lon'])
		print(location)
		new_branch = RestaurantBranch.objects.create(branch_name=self.cleaned_data['branchName'],
		                                             branch_location=location)
		print(new_branch)
		try:
			new_branch.branch_location_details = self.cleaned_data['extra_details']
		except Exception:
			pass
		if commit:
			new_branch.save()
		return new_branch
# branch location field

accounts/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.shortcuts import redirect, render
from django.views.generic import TemplateView
from django.views.generic.base import View
from geopy.geocoders import Nominatim

from accounts.account_links import *
from accounts.models import *
from accounts.utils import *
from .forms import UserForm

geolocator = Nominatim(user_agent="foodsquare")

from django.core.mail import send_mail


def recoveryRender(request):
	return HttpResponse("Enter email to recover !!!")


def homepageRender(request):
	return render(request, USER_DASHBOARD_PAGE)


class LoginView(TemplateView):
	template_name = 'accounts/login_v4.html'

	def get(self, request, *args, **kwargs):
		if self.request.user.is_authenticated:
			return redirect('/')
		else:
			return super().get(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		ctx = {'loggedIn': self.request.user.is_authenticated}
		return ctx

	def post(self, request, *args, **kwargs):
		print(pretty_request(request))
		username = request.POST.get('username', False)
		password = request.POST.get('pass', False)
		if username and password:
			user = authenticate(request, username=username, password=password)
			if user is not None and user.is_customer:
				login(request, user)
				print('Signing in: ' + str(request.user))
				return redirect('/')
			elif user is None:
				return render(request, 'accounts/message_page.html',
				              {'header': "Error !", 'details': 'Invalid Username or Password',
				               'redirect': reverse('accounts:login')})
			# return JsonResponse({'account': False})
			elif not user.is_customer:
				return render(request, 'accounts/message_page.html',
				              {'header': "Error !", 'details': 'Not a Customer account',
				               'redirect': reverse('accounts:login')})
		# return JsonResponse({'account': True, 'customer': False})
		else:
			return render(request, 'accounts/message_page.html',
			              {'header': "Error !", 'details': 'Username or password is empty',
			               'redirect': reverse('accounts:login')})


class ManagerLoginView(TemplateView):
	template_name = 'accounts/Manager_Login.html'

	def get(self, request, *args, **kwargs):
		if self.request.user.is_authenticated:
			return redirect('/homepage')
		else:
			return super().get(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		ctx = {'loggedIn': self.request.user.is_authenticated}
		return ctx

	def post(self, request, *args, **kwargs):
		print(pretty_request(request))
		username = request.POST.get('username', False)
		password = request.POST.get('pass', False)
		if username and password:
			user = authenticate(request, username=username, password=password)
			if user is None:
				return render(request, 'accounts/message_page.html',
				              {'header': "Error !", 'details': 'Invalid Username or Password',
				               'redirect': reverse('accounts:manger_login')})
			if user.is_branch_manager:
				login(request, user)
				print('Signing in: ' + str(request.user))
				return redirect('/orders')
			elif user.is_manager:
				rest = Restaurant.objects.get(user=user)
				if rest.restaurant_key.strip() != '0':
					login(request, user)
					print('Signing in: ' + str(request.user))
					return redirect('/homepage')
				elif rest.restaurant_key.strip() == '0':
					return render(request, 'accounts/message_page.html',
					              {'header': "Error !", 'details': 'Your account has not been approved yet'})
			elif not user.is_manager or not user.is_branch_manager:
				return render(request, 'accounts/message_page.html',
				              {'header': "Error !", 'details': 'Not a Manager or Branch Manager account',
				               'redirect': reverse('accounts:manger_login')})
			else:
				return render(request, 'accounts/message_page.html',
				              {'header': "Error !", 'details': 'User authentication error',
				               'redirect': reverse('accounts:manger_login')})
		else:
			return render(request, 'accounts/message_page.html',
			              {'header': "Error !", 'details': ' Username or password is empty',
			               'redirect': reverse('accounts:manger_login')})


class DeliveryLoginView(TemplateView):
	template_name = 'accounts/Delivery_Login.html'

	def get(self, request, *args, **kwargs):
		if self.request.user.is_authenticated:
			return redirect('/orders')
		else:
			return super().get(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		ctx = {'loggedIn': self.request.user.is_authenticated}
		return ctx

	def post(self, request, *args, **kwargs):
		print(pretty_request(request))
		username = request.POST.get('username', False)
		password = request.POST.get('pass', False)
		if username and password:
			user = authenticate(request, username=username, password=password)
			if user and user.is_delivery_man:
				login(request, user)
				print('Signing in: ' + str(request.user))
				return redirect('/orders')
			else:
				return render(request, 'accounts/message_page.html',
				              {'header': "Error !", 'details': '  User authentication error',
				               'redirect': reverse('accounts:delivery_login')})

		else:
			return render(request, 'accounts/message_page.html',
			              {'header': "Error !", 'details': ' Username or password is empty',
			               'redirect': reverse('accounts:delivery_login')})


class AdminLoginView(TemplateView):
	template_name = 'accounts/Manager_Login.html'

	def get(self, request, *args, **kwargs):
		if self.request.user.is_authenticated:
			return redirect('/homepage')
		else:
			return super().get(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		ctx = {'loggedIn': self.request.user.is_authenticated}
		return ctx

	def post(self, request, *args, **kwargs):
		print(pretty_request(request))
		username = request.POST.get('username', False)
		password = request.POST.get('pass', False)
		if username and password:
			user = authenticate(request, username=username, password=password)
			if user is not None and user.is_superuser:
				login(request, user)
				print('Signing in: ' + str(request.user))
				return redirect('/homepage')
			elif not user.is_superuser:
				return render(request, 'accounts/message_page.html',
				              {'header': "Error !", 'details': ' Not an admin account'})
			else:
				return render(request, 'accounts/message_page.html',
				              {'header': "Error !", 'details': '  User authentication error'})
		else:
			return render(request, 'accounts/message_page.html',
			              {'header': "Error !", 'details': ' Username or password is empty'})


class RegisterView(TemplateView):
	template_name = 'accounts/colorlib-regform-7.html'

	def get(self, request, *args, **kwargs):
		if self.request.user.is_authenticated:
			return redirect('/')
		else:
			return super().get(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		ctx = super(RegisterView, self).get_context_data(**kwargs)
		ctx['user_form'] = UserForm(prefix='user')
		# ctx['profile_form'] = ProfileForm(prefix='profile')
		ctx = {'loggedIn': self.request.user.is_authenticated}
		return ctx

	def post(self, request, *args, **kwargs):
		print(pretty_request(request))

		user_form = UserForm(request.POST)

		if user_form.is_valid():
			user = user_form.save(commit=False)
			user.is_customer = True
			user.save()
			p = UserProfile.objects.create(user=user)
			p.save()
			print('Registering : ' + str(request.user))
			login(request, user)
			return redirect('/')
		else:
			return render(request, 'accounts/message_page.html',
			              {'header': "Error !", 'details': ' signup'})


class ManagerRegisterView(TemplateView):
	template_name = 'accounts/Manager_Registration_form.html'

	def get(self, request, *args, **kwargs):
		if self.request.user.is_authenticated:
			return redirect('/')
		else:
			return super().get(request, *args, **kwargs)

	def get_context_data(self, **kwargs):
		ctx = super(ManagerRegisterView, self).get_context_data(**kwargs)
		ctx['user_form'] = UserForm(prefix='user')
		# ctx['profile_form'] = ProfileForm(prefix='profile')
		ctx = {'loggedIn': self.request.user.is_authenticated}
		return ctx

	def post(self, request, *args, **kwargs):
		print(pretty_request(request))

		if request.POST.get('password') != request.POST.get('re_pass'):
			return

		user_form = UserForm(request.POST)
		user = None
		if user_form.is_valid():
			user = user_form.save(commit=False)
			user.is_manager = True
			send_mail(
				'Account Activation Pending',
				'You have applied for creating a Restaurant Account.\n '
				'Username:' + user.username + '\n ' +
				'Email:' + user.email + '\n ' +
				'Password:' + request.POST.get('password') + '\n ' +
				'Restaurant:' + request.POST['rest_name'] + '\n ' +
				'Trade License:' + request.POST['trade_license'] + '\n ' +
				'We are verifying your information.\n ' +
				'You will be notified via this email when we are done.',
				'accounts@foodsquare',
				[user.email],
				fail_silently=False,
			)

			user.save()
			rest = Restaurant()
			rest.restaurant_name = request.POST['rest_name']
			rest.trade_license = request.POST['trade_license']

			rest.user = user
			rest.save()
			from webAdmin.utils import send_notification_to_admin
			send_notification_to_admin(rest.restaurant_name + "'s registration is pending for approval")
			return render(request, 'accounts/message_page.html',
			              {'header': "Registration Pending", 'details': 'Check your inbox (' + user.email + ')'})
		else:
			return render(request, 'accounts/message_page.html',
			              {'header': "Registration Failed!!!", 'details': 'Invalid Form Data'})


class DeliveryRegister(TemplateView):
	template_name = 'accounts/Delivery_Registration_Form.html'

	def get(self, request, *args, **kwargs):

accounts/templates/accounts/Delivery_Login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% if not loggedIn %}
        <title>Login V4</title>
        <meta charset="UTF-8">
        {% load static %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--===============================================================================================-->
        <link rel="icon" type="image/png" href="{% static 'accounts/login_v4/images/icons/favicon.ico' %}"/>
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css"
              href="{% static 'accounts/login_v4/vendor/bootstrap/css/bootstrap.min.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css"
              href="{% static 'accounts/login_v4/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css"
              href="{% static 'accounts/login_v4/fonts/iconic/css/material-design-iconic-font.min.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/login_v4/vendor/animate/animate.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css"
              href="{% static 'accounts/login_v4/vendor/css-hamburgers/hamburgers.min.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css"
              href="{% static 'accounts/login_v4/vendor/animsition/css/animsition.min.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/login_v4/vendor/select2/select2.min.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css"
              href="{% static 'accounts/login_v4/vendor/daterangepicker/daterangepicker.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/login_v4/css/util.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/login_v4/css/main.css' %}">
        <!--===============================================================================================-->
    {% else %}
        <meta http-equiv='refresh' content='2; URL=/'>
    {% endif %}
</head>
<body>
{% if not loggedIn %}
    <div class="limiter">
        <div class="container-login100">
            {#            style="background-image: url('static/accounts/login_v4/images/bg-01.jpg');"#}
            <div class="wrap-login100 p-l-55 p-r-55 p-t-15 p-b-20">
                <form class="login100-form validate-form" method="post">
                    {% csrf_token %}
                    <a class="login100-form-title p-b-20" href="/">
                        Foodsquare
                    </a>

                    <div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">
                        <span class="label-input100">Username</span>
                        <input class="input100" type="text" name="username" placeholder="Type your username">
                        <span class="focus-input100" data-symbol="&#xf206;"></span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate="Password is required">
                        <span class="label-input100">Password</span>
                        <input class="input100" type="password" name="pass" placeholder="Type your password">
                        <span class="focus-input100" data-symbol="&#xf190;"></span>
                    </div>

                    <div class="text-right p-t-8 p-b-31">
                        <a href="/accounts/recovery/">
                            Forgot password?
                        </a>
                    </div>

                    <div class="container-login100-form-btn">
                        <div class="wrap-login100-form-btn">
                            <div class="login100-form-bgbtn"></div>
                            <button class="login100-form-btn">
                                Login
                            </button>
                        </div>
                    </div>

                    <div class="flex-col-c p-t-20">
                        <a class="txt1">
                            Don't have an account yet?
                        </a>
                        <b><u><a href="{% url 'accounts:delivery_register' %}" class="txt2">
                            Create New Account
                        </a></u></b>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div id="dropDownSelect1"></div>
    <!--===============================================================================================-->
    <script src="{% static 'accounts/login_v4/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'accounts/login_v4/vendor/animsition/js/animsition.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'accounts/login_v4/vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'accounts/login_v4/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'accounts/login_v4/vendor/select2/select2.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'accounts/login_v4/vendor/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'accounts/login_v4/vendor/daterangepicker/daterangepicker.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'accounts/login_v4/vendor/countdowntime/countdowntime.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'accounts/login_v4/js/main.js' %}"></script>
{% else %}
    <b>You are already signed in...</b>
{% endif %}
</body>
</html>

accounts/templates/accounts/Manager_Login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% if not loggedIn %}
        <title>Login V4</title>
        <meta charset="UTF-8">
        {% load static %}
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <!--===============================================================================================-->
        <link rel="icon" type="image/png" href="{% static 'accounts/login_v4/images/icons/favicon.ico' %}"/>
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css"
              href="{% static 'accounts/login_v4/vendor/bootstrap/css/bootstrap.min.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css"
              href="{% static 'accounts/login_v4/fonts/font-awesome-4.7.0/css/font-awesome.min.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css"
              href="{% static 'accounts/login_v4/fonts/iconic/css/material-design-iconic-font.min.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/login_v4/vendor/animate/animate.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css"
              href="{% static 'accounts/login_v4/vendor/css-hamburgers/hamburgers.min.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css"
              href="{% static 'accounts/login_v4/vendor/animsition/css/animsition.min.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/login_v4/vendor/select2/select2.min.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css"
              href="{% static 'accounts/login_v4/vendor/daterangepicker/daterangepicker.css' %}">
        <!--===============================================================================================-->
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/login_v4/css/util.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'accounts/login_v4/css/main.css' %}">
        <!--===============================================================================================-->
    {% else %}
        <meta http-equiv='refresh' content='2; URL=/'>
    {% endif %}
</head>
<body>
{% if not loggedIn %}
    <div class="limiter">
        <div class="container-login100">
            {#            style="background-image: url('static/accounts/login_v4/images/bg-01.jpg');"#}
            <div class="wrap-login100 p-l-55 p-r-55 p-t-15 p-b-20">
                <form class="login100-form validate-form" method="post">
                    {% csrf_token %}
                    <a class="login100-form-title p-b-20" href="/">
                        Foodsquare
                    </a>

                    <div class="wrap-input100 validate-input m-b-23" data-validate="Username is reauired">
                        <span class="label-input100">Username</span>
                        <input class="input100" type="text" name="username" placeholder="Type your username">
                        <span class="focus-input100" data-symbol="&#xf206;"></span>
                    </div>

                    <div class="wrap-input100 validate-input" data-validate="Password is required">
                        <span class="label-input100">Password</span>
                        <input class="input100" type="password" name="pass" placeholder="Type your password">
                        <span class="focus-input100" data-symbol="&#xf190;"></span>
                    </div>

                    <div class="text-right p-t-8 p-b-31">
                        <a href="/accounts/recovery/">
                            Forgot password?
                        </a>
                    </div>

                    <div class="container-login100-form-btn">
                        <div class="wrap-login100-form-btn">
                            <div class="login100-form-bgbtn"></div>
                            <button class="login100-form-btn">
                                Login
                            </button>
                        </div>
                    </div>


                    <div class="flex-col-c p-t-20">
                        <a class="txt1">
                            Don't have an account yet?
                        </a>
                        <b><u><a href="/accounts/manager_register/" class="txt2">
                            Create New Account
                        </a></u></b>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <div id="dropDownSelect1"></div>
    <!--===============================================================================================-->
    <script src="{% static 'accounts/login_v4/vendor/jquery/jquery-3.2.1.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'accounts/login_v4/vendor/animsition/js/animsition.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'accounts/login_v4/vendor/bootstrap/js/popper.js' %}"></script>
    <script src="{% static 'accounts/login_v4/vendor/bootstrap/js/bootstrap.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'accounts/login_v4/vendor/select2/select2.min.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'accounts/login_v4/vendor/daterangepicker/moment.min.js' %}"></script>
    <script src="{% static 'accounts/login_v4/vendor/daterangepicker/daterangepicker.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'accounts/login_v4/vendor/countdowntime/countdowntime.js' %}"></script>
    <!--===============================================================================================-->
    <script src="{% static 'accounts/login_v4/js/main.js' %}"></script>
{% else %}
    <b>You are already signed in...</b>
{% endif %}
</body>
</html>